### ISSUE TITLE
安装SAM 节点，但是提示CUDA环境设置不对，如何处理？

### ISSUE THREAD

**Issue by se7enth** [YanWenKun/ComfyUI-Docker#1]
装mmcv遇到的问题

报错信息如下：
 python setup.py egg_info did not run successfully.
2023-04-19 20:21:11   │ exit code: 1
2023-04-19 20:21:11   ╰─> [14 lines of output]
2023-04-19 20:21:11       Traceback (most recent call last):
2023-04-19 20:21:11         File "<string>", line 2, in <module>
2023-04-19 20:21:11         File "<pip-setuptools-caller>", line 34, in <module>
2023-04-19 20:21:11         File "/tmp/pip-install-t972ixw_/mmcv_bdf1756711d24da4961cc35164bc36cf/setup.py", line 343, in <module>
2023-04-19 20:21:11           ext_modules=get_extensions(),
2023-04-19 20:21:11         File "/tmp/pip-install-t972ixw_/mmcv_bdf1756711d24da4961cc35164bc36cf/setup.py", line 304, in get_extensions
2023-04-19 20:21:11           ext_ops = extension(
2023-04-19 20:21:11         File "/usr/lib64/python3.10/site-packages/torch/utils/cpp_extension.py", line 1051, in CUDAExtension
2023-04-19 20:21:11           library_dirs += library_paths(cuda=True)
2023-04-19 20:21:11         File "/usr/lib64/python3.10/site-packages/torch/utils/cpp_extension.py", line 1178, in library_paths
2023-04-19 20:21:11           if (not os.path.exists(_join_cuda_home(lib_dir)) and
2023-04-19 20:21:11         File "/usr/lib64/python3.10/site-packages/torch/utils/cpp_extension.py", line 2227, in _join_cuda_home
2023-04-19 20:21:11           raise EnvironmentError('CUDA_HOME environment variable is not set. '
2023-04-19 20:21:11       OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
2023-04-19 20:21:11       [end of output]

**Comment by YanWenKun** [comment]
首先启动一个容器并进入 root bash

```
docker run -it --gpus all \
  -v "$(pwd)"/storage:/home/runner \
  -p 8188:8188 \
  -e CLI_ARGS="" \
  --user root \
  yanwk/comfyui-boot:latest /bin/bash
```

然后使用这个命令 ([doc](https://mmcv.readthedocs.io/zh_CN/latest/get_started/installation.html#pip)) 安装
```sh
pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html
```

**Comment by se7enth** [comment]
> 首先启动一个容器并进入 root bash
> 
> ```
> docker run -it --gpus all \
>   -v "$(pwd)"/storage:/home/runner \
>   -p 8188:8188 \
>   -e CLI_ARGS="" \
>   --user root \
>   yanwk/comfyui-boot:latest /bin/bash
> ```
> 
> 然后使用这个命令 ([doc](https://mmcv.readthedocs.io/zh_CN/latest/get_started/installation.html#pip)) 安装
> 
> ```shell
> pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html
> ```

这是新创建了一个容器，我原来已经改过一点设置，安装过一些依赖，新建这个容器不能正常运行comfyui。但是可以正确安装mmcv，我注意到添加 --gpus all 参数，所以我在docker compose配置里添加这个参数以后，重新compose 了，用docker exec 拿到root 再在容器里成功安装。另外这个impact-pack，安装pycocotools-2.0.6也有个坑，编译不成功。最后在这https://github.com/Bing-su/dddetailer/blob/d4e58f3e8f22f3ddbc81fc12c713ff54483efb2f/install.py 找了WHL安装搞定。

**Comment by YanWenKun** [comment]
很高兴你安装成功了。我给今后 Google 到这里的人补充一下：

> 新建这个容器不能正常运行comfyui

安装完后运行：
```
su runner -c 'bash /home/scripts/entrypoint.sh'
```

如果需要安装的东西较多，建议修改 `Dockerfile` 来构建自己的镜像，可以本地构建，也可以利用 GitHub Actions 构建并发布到 Docker Hub，再下载镜像。
