### ISSUE TITLE
Unable to launch megapack since v4.0 (ValueError: numpy.dtype)

### ISSUE THREAD

**Issue by matiasba** [YanWenKun/ComfyUI-Docker#36]
Im unable to start the megapack image since the v4.0 update. Here is the error log
```
## ComfyUI-Manager: installing dependencies done.
[2024-06-25 03:17] ** ComfyUI startup time: 2024-06-25 03:17:51.830209
[2024-06-25 03:17] ** Platform: Linux
[2024-06-25 03:17] ** Python version: 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC]
[2024-06-25 03:17] ** Python executable: /usr/bin/python3
[2024-06-25 03:17] ** Log path: /root/comfyui.log
[2024-06-25 03:17] 
Prestartup times for custom nodes:
[2024-06-25 03:17]    0.0 seconds: /root/ComfyUI/custom_nodes/rgthree-comfy
[2024-06-25 03:17]    5.4 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-06-25 03:17] 
Total VRAM 12037 MB, total RAM 63262 MB
[2024-06-25 03:17] pytorch version: 2.3.0+cu121
[2024-06-25 03:17] 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/root/./ComfyUI/main.py", line 76, in <module>
    import execution
  File "/root/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/root/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/root/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/root/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/root/ComfyUI/comfy/model_management.py", line 139, in <module>
    import xformers
  File "/usr/lib64/python3.11/site-packages/xformers/__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "/usr/lib64/python3.11/site-packages/xformers/checkpoint.py", line 25, in <module>
    from scipy.optimize import Bounds, LinearConstraint, milp
  File "/usr/lib64/python3.11/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._optimize import *
  File "/usr/lib64/python3.11/site-packages/scipy/optimize/_optimize.py", line 35, in <module>
    from scipy.linalg import cholesky, issymmetric, LinAlgError
  File "/usr/lib64/python3.11/site-packages/scipy/linalg/__init__.py", line 203, in <module>
    from ._misc import *
  File "/usr/lib64/python3.11/site-packages/scipy/linalg/_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/usr/lib64/python3.11/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
[2024-06-25 03:17] Traceback (most recent call last):
[2024-06-25 03:17]   File "/usr/lib64/python3.11/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
[2024-06-25 03:17]     raise ImportError(msg)
[2024-06-25 03:17] ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

[2024-06-25 03:17] 
[2024-06-25 03:17] 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/root/./ComfyUI/main.py", line 76, in <module>
    import execution
  File "/root/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/root/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/root/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/root/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/root/ComfyUI/comfy/model_management.py", line 139, in <module>
    import xformers
  File "/usr/lib64/python3.11/site-packages/xformers/__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "/usr/lib64/python3.11/site-packages/xformers/checkpoint.py", line 464, in <module>
    class SelectiveCheckpointWrapper(ActivationWrapper):
  File "/usr/lib64/python3.11/site-packages/xformers/checkpoint.py", line 481, in SelectiveCheckpointWrapper
    @torch.compiler.disable
  File "/usr/lib64/python3.11/site-packages/torch/compiler/__init__.py", line 96, in disable
    import torch._dynamo
  File "/usr/lib64/python3.11/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "/usr/lib64/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 40, in <module>
    from . import config, exc, trace_rules
  File "/usr/lib64/python3.11/site-packages/torch/_dynamo/trace_rules.py", line 50, in <module>
    from .variables import (
  File "/usr/lib64/python3.11/site-packages/torch/_dynamo/variables/__init__.py", line 34, in <module>
    from .higher_order_ops import (
  File "/usr/lib64/python3.11/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 13, in <module>
    import torch.onnx.operators
  File "/usr/lib64/python3.11/site-packages/torch/onnx/__init__.py", line 59, in <module>
    from ._internal.onnxruntime import (
  File "/usr/lib64/python3.11/site-packages/torch/onnx/_internal/onnxruntime.py", line 37, in <module>
    import onnxruntime  # type: ignore[import]
  File "/usr/lib64/python3.11/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/lib64/python3.11/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
[2024-06-25 03:17] AttributeError: _ARRAY_API not found
[2024-06-25 03:18] xformers version: 0.0.26.post1
[2024-06-25 03:18] Set vram state to: NORMAL_VRAM
[2024-06-25 03:18] Device: cuda:0 NVIDIA RTX A2000 12GB : cudaMallocAsync
[2024-06-25 03:18] Using xformers cross attention
[2024-06-25 03:18] Traceback (most recent call last):
[2024-06-25 03:18]   File "/root/./ComfyUI/main.py", line 76, in <module>
[2024-06-25 03:18]     import execution
[2024-06-25 03:18]   File "/root/ComfyUI/execution.py", line 11, in <module>
[2024-06-25 03:18]     import nodes
[2024-06-25 03:18]   File "/root/ComfyUI/nodes.py", line 22, in <module>
[2024-06-25 03:18]     import comfy.samplers
[2024-06-25 03:18]   File "/root/ComfyUI/comfy/samplers.py", line 1, in <module>
[2024-06-25 03:18]     from .k_diffusion import sampling as k_diffusion_sampling
[2024-06-25 03:18]   File "/root/ComfyUI/comfy/k_diffusion/sampling.py", line 3, in <module>
[2024-06-25 03:18]     from scipy import integrate
[2024-06-25 03:18]   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
[2024-06-25 03:18]   File "/usr/lib64/python3.11/site-packages/scipy/__init__.py", line 134, in __getattr__
[2024-06-25 03:18]     return _importlib.import_module(f'scipy.{name}')
[2024-06-25 03:18]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-25 03:18]   File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
[2024-06-25 03:18]     return _bootstrap._gcd_import(name[level:], package, level)
[2024-06-25 03:18]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-25 03:18]   File "/usr/lib64/python3.11/site-packages/scipy/integrate/__init__.py", line 94, in <module>
[2024-06-25 03:18]     from ._quadrature import *
[2024-06-25 03:18]   File "/usr/lib64/python3.11/site-packages/scipy/integrate/_quadrature.py", line 9, in <module>
[2024-06-25 03:18]     from scipy.special import roots_legendre
[2024-06-25 03:18]   File "/usr/lib64/python3.11/site-packages/scipy/special/__init__.py", line 777, in <module>
[2024-06-25 03:18]     from . import _ufuncs
[2024-06-25 03:18]   File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs
[2024-06-25 03:18] ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
It seems to be some dependency problem https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from

**Comment by YanWenKun** [comment]
Thank you! It's fixed now :-)
