### ISSUE TITLE
cu124-megpak - ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PeterTF656** [YanWenKun/ComfyUI-Docker#56]
@YanWenKun 

```
########################################
[INFO] Starting ComfyUI...
########################################
Traceback (most recent call last):
  File "/root/ComfyUI/main.py", line 87, in <module>
    import comfy.utils
  File "/root/ComfyUI/comfy/utils.py", line 20, in <module>
    import torch
  File "/usr/local/lib64/python3.12/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory
```

**Comment by guystreeter** [comment]
You might be using CUDA version 12.6. The `nvidia-smi` command will report your version. the cu124 container is for CUDA 12.4.
I am not aware of a 12.6 version.

**Comment by YanWenKun** [comment]
Thanks!
It's a PATH problem caused by OS update, and was just fixed :-)
