### ISSUE TITLE
unable installl custom nodes throught comfyui manager

### ISSUE THREAD

**Issue by jimlee2002** [YanWenKun/ComfyUI-Docker#9]
![image](https://github.com/YanWenKun/ComfyUI-Docker/assets/21117946/ceb9b18a-f87c-4f47-abee-ed91ca3ea670)

```
FETCH DATA from: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Install custom node 'ComfyUI Impact Pack'
install: ['https://github.com/ltdrdata/ComfyUI-Impact-Pack']
Download: git clone 'https://github.com/ltdrdata/ComfyUI-Impact-Pack'
Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Impact-Pack / name 'git' is not defined
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```

Maybe missing some python packages like `GitPython`? I saw these following error messages from log when comfyui launch:

```
## ComfyUI-Manager: installing dependencies
[!] error: externally-managed-environment
[!] 
[!] × This environment is externally managed
[!] ╰─> To install Python packages system-wide, try
[!]     zypper install python311-xyz, where xyz is the package
[!]     you are trying to install.
[!]     
[!]     If you wish to install a non-rpm packaged Python package,
[!]     create a virtual environment using python3.11 -m venv path/to/venv.
[!]     Then use path/to/venv/bin/python and path/to/venv/bin/pip.
[!]     
[!]     If you wish to install a non-rpm packaged Python application,
[!]     it may be easiest to use `pipx install xyz`, which will manage a
[!]     virtual environment for you. Install pipx via `zypper install python311-pipx` .
[!] 
[!] note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
[!] hint: See PEP 668 for the detailed specification.
## [ERROR] ComfyUI-Manager: Attempting to reinstall dependencies using an alternative method.
[!] error: externally-managed-environment
[!] 
[!] × This environment is externally managed
[!] ╰─> To install Python packages system-wide, try
[!]     zypper install python311-xyz, where xyz is the package
[!]     you are trying to install.
[!]     
[!]     If you wish to install a non-rpm packaged Python package,
[!]     create a virtual environment using python3.11 -m venv path/to/venv.
[!]     Then use path/to/venv/bin/python and path/to/venv/bin/pip.
[!]     
[!]     If you wish to install a non-rpm packaged Python application,
[!]     it may be easiest to use `pipx install xyz`, which will manage a
[!]     virtual environment for you. Install pipx via `zypper install python311-pipx` .
[!] 
[!] note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
[!] hint: See PEP 668 for the detailed specification.
## [ERROR] ComfyUI-Manager: Failed to install the GitPython package in the correct Python environment. Please install it manually in the appropriate environment. (You can seek help at https://app.element.io/#/room/%23comfyui_space%3Amatrix.org)
## ComfyUI-Manager: installing dependencies done.
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "/home/runner/ComfyUI/custom_nodes/comfyui_controlnet_aux/utils.py", line 4, in <module>
    import cv2
  File "/usr/lib64/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/lib64/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

Cannot import /home/runner/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by lingfengchencn** [comment]
I got the same issue

```
comfyui  | Install custom node 'ComfyUI Impact Pack'
comfyui  | install: ['https://github.com/ltdrdata/ComfyUI-Impact-Pack']
comfyui  | Download: git clone 'https://github.com/ltdrdata/ComfyUI-Impact-Pack'
comfyui  | Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Impact-Pack / name 'git' is not defined
comfyui  | FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

```
